theme: jekyll-theme-cayman
title: MSF 2025 Conference
description: Colloque International en Management, Finance et Comptabilité – Hammamet, June 19–21, 2025
<div align="center">
  <img src="Image1.png" alt="Université de Sfax" height="60" style="margin: 20px;" />

</div>
